# Generated by Django 4.2.20 on 2025-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagen',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagen',
            name='ensamblada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagen',
            name='url_archivo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
