# Generated by Django 4.2.19 on 2025-03-14 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagen',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagen',
            name='url_gcp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImagenChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('archivo_chunk', models.BinaryField()),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='uploads.imagen')),
            ],
        ),
    ]
